name: your-horror-nobel-backend

services:
  backend:
    container_name: your-horror-nobel-backend-container
    build: .
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=service-account-key.json
      - GOOGLE_CLOUD_PROJECT=your-horror-nobel
    # 開発環境用: --reloadフラグ付きでホットリロード有効
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]